Fix editor-test-helpers type errors
'Error TS2742: The inferred type of 'shallowWithIntl' cannot be named
without a reference to 'enzyme/node_modules/@types/react'. This is
likely not portable. A type annotation is necessary.'

Since this package is private, we can probably remove the
build/tsconfig.json entirely.